#include "WJLSD.h"
#include "WJLHA3.h"
// Random - generated byte 2D table,Customizable tables
unsigned char SDRandomOfUCharTable[256] =	{
	226,134,150,101,199,177,118,188,179,220,74,27,95,216,14,166,
	23,81,214,203,151,41,224,31,141,108,56,92,135,120,196,9,
	178,162,110,146,76,3,79,217,206,208,87,94,246,41,147,112,
	119,217,75,34,193,94,147,238,174,5,104,130,236,219,117,58,
	246,200,185,153,22,8,184,34,96,14,165,158,236,169,251,88,
	123,45,60,68,141,71,29,164,177,32,102,111,236,96,182,13,
	128,172,9,20,33,73,75,232,125,137,150,65,105,232,158,250,
	62,190,168,176,65,159,18,33,111,196,152,116,241,4,253,43,
	197,25,52,130,77,92,95,231,147,87,2,63,168,226,91,123,
	40,15,178,77,50,74,93,141,65,217,184,59,44,23,232,235,
	59,112,27,214,194,178,79,149,203,193,251,64,116,91,237,102,
	99,85,119,12,65,72,170,209,141,96,190,254,38,182,184,89,
	240,114,162,60,145,163,252,178,186,155,235,240,207,119,137,208,
	151,92,48,210,165,220,6,60,145,225,14,4,153,136,7,108,
	105,68,240,32,149,185,156,28,74,211,208,154,235,158,171,187,
	232,176,146,167,233,251,202,120,107,41,232,78,124,188,186,143
};
// Initialize structure
void InitializeWJLDeCoder(WJLDeCoder *coder, unsigned char *InByteArray, unsigned int InByteArray_length)
{
	int i, n;
	unsigned int values = 0;
	coder->rangeCodeBitsLenght = 31;
	coder->rangeCodeShiftBitsLenght = coder->rangeCodeBitsLenght - 8;
	coder->rangeCodeMaxIterval = 1 << coder->rangeCodeBitsLenght;
	coder->rangeCodeMinIterval = 1 << coder->rangeCodeShiftBitsLenght;
	coder->counterMaxFreq = 0x00FFFFL;
	coder->symbolsMaxCount = 256;
	coder->coefficient = 1.0;
	coder->encodeFlow = 0;
	coder->encodeFlowRange = coder->rangeCodeMaxIterval;
	coder->encodeDelay = 0;
	coder->encodeDelayCount = 0;
	coder->encodeOutBufferLoop = 0;
	coder->decodeInBufferLoop = 0;
	coder->decodeOutBufferLoop = 0;
	coder->Total = 0;
	coder->CumFreq = 0;
	coder->Freq = 0;
	coder->values = 0;
	coder->Result = 0;
	coder->SymbolsFreqArray = (unsigned int *)malloc(sizeof(unsigned int) * (coder->symbolsMaxCount + 1));
	for(i = 0; i <= coder->symbolsMaxCount; ++i){
		coder->SymbolsFreqArray[i] = 1;
	}
	// Total is the Sum of all symbol's freq
	coder->Total = coder->symbolsMaxCount + 1;
	// Initialize the OutBufferArray
	coder->decodeOutBufferArray = (unsigned char *)malloc(InByteArray_length);
	// load the first 4bytes in InByteArray
	n = 32;
	do {
		n -= 8;
		values = (values << 8) | (unsigned char)InByteArray[coder->decodeInBufferLoop];
		coder->decodeInBufferLoop = coder->decodeInBufferLoop + 1;
	} while ( n > 0 );
	coder->values = values;
}
// Query 'SERandomOfUCharTable' table function
double getDeCoefficient(int index, unsigned char Symbol, unsigned char OneKeytByte)
{
	return 1.0 - (double)(SDRandomOfUCharTable[ (index + Symbol) % 256 ] ^  OneKeytByte) / (100000.0 + OneKeytByte);
};
// bytes decoding output
void OutPutDecode(WJLDeCoder *coder, int ucByte)
{
	coder->decodeOutBufferArray[coder->decodeOutBufferLoop] = (unsigned char)ucByte;
	coder->decodeOutBufferLoop = coder->decodeOutBufferLoop + 1;
}
// When coding, calculate frequency
void DeGetFreq(WJLDeCoder *coder)
{
	int i = 0;
	unsigned int Sum = 0;
	if(coder->Result == 0){
		coder->CumFreq = 0;
		coder->Freq = coder->SymbolsFreqArray[0];
		return;
	}
	// get the cumulative distribution function
	for(i = 0; i < coder->Result; ++i) {
		Sum += coder->SymbolsFreqArray[i];
	}
	coder->Freq = coder->SymbolsFreqArray[coder->Result];
	coder->CumFreq = Sum;
}
// Get Distribution Function
void GetDistributionFunction(WJLDeCoder *coder)
{
	int i = 0;
	unsigned int Sum = 0;
	unsigned int result = 0;
	unsigned int Code =coder->values >> 1;
	if(coder->encodeFlowRange == 0){
		return;
	}
	coder->encodeFlowRange = coder->encodeFlowRange / coder->Total;
	coder->encodeFlowRange = (unsigned int)((double)coder->encodeFlowRange * coder->coefficient);

	if (Code < coder->encodeFlow) {
		result = (Code + coder->rangeCodeMaxIterval - coder->encodeFlow) / coder->encodeFlowRange;
	} else {
		result = (Code - coder->encodeFlow) / coder->encodeFlowRange;
	}
	if(result < coder->SymbolsFreqArray[0]) {
		coder->Result = 0x00;
		return;
	}
	// find the symbol
	for(i = 0; i < coder->symbolsMaxCount; ++i) {
		Sum += coder->SymbolsFreqArray[i];
		if(result >= Sum && result < ( Sum + coder->SymbolsFreqArray[i + 1] ) ) {
			coder->Result = i + 1;
			return;
		}
	}
}
// Cumulative and reduced frequency
void DeIncFreq(WJLDeCoder *coder)
{
	int i = 0;
	unsigned int NewFreq = 0, Sum = 0;
	// Synchronously subtracts the statistics of each symbol
	if(coder->Total == coder->counterMaxFreq){
		for(i = 0; i <= coder->symbolsMaxCount; ++i) {
			NewFreq = coder->SymbolsFreqArray[i] >> 1;
			if(NewFreq == 0) {
				coder->SymbolsFreqArray[i] = 1;
			}else{
				coder->SymbolsFreqArray[i] = NewFreq;
			}
			Sum += coder->SymbolsFreqArray[i];
		}
		coder->Total = Sum;
	}
	// this symbol freq Add 1
	coder->SymbolsFreqArray[coder->Result] ++;
	// All symbol freq Add 1
	coder->Total += 1;
}
// update Range
void DeDecode(WJLDeCoder *coder, unsigned char *InBytesArray, unsigned int InBytesArray_Length)
{
	coder->encodeFlow += coder->CumFreq * coder->encodeFlowRange;
	coder->encodeFlowRange *= coder->Freq;
	while (coder->encodeFlowRange <=  coder->rangeCodeMinIterval){
		coder->encodeFlow = (coder->encodeFlow << 8) & (coder->rangeCodeMaxIterval - 1);
		coder->encodeFlowRange = coder->encodeFlowRange << 8;
		if(coder->decodeInBufferLoop < InBytesArray_Length){
			coder->values = (coder->values << 8) | InBytesArray[coder->decodeInBufferLoop];
			coder->decodeInBufferLoop = coder->decodeInBufferLoop + 1;
		}else{
			return;
		}
	}
}
// decoded a symbol
void decryptingasymbol(WJLDeCoder *coder, unsigned char *InBytesArray, unsigned int InBytesArray_Length)
{
	GetDistributionFunction(coder);
	DeGetFreq(coder);
	DeDecode(coder, InBytesArray, InBytesArray_Length);
	DeIncFreq(coder);
}
// decoded the RandomBytes by InByteArray
int decryptingRandomBytes(WJLDeCoder *coder,const char *passwords, int passwords_Length, unsigned char *InBytesArray, unsigned int InBytesArray_Length,unsigned int RandomBuFF_Length)
{
	int i = 0;
	unsigned char *keytBuFF;
	keytBuFF = (unsigned char *)malloc(RandomBuFF_Length);
	WJLHA3((unsigned char *)passwords, passwords_Length, SDRandomOfUCharTable, 256, keytBuFF, RandomBuFF_Length);
	// decoding
	for(i = 0; i < RandomBuFF_Length; ++i){
		coder->coefficient = getDeCoefficient(i, (keytBuFF[i % RandomBuFF_Length] + i ) % 0xFF, keytBuFF[ i % RandomBuFF_Length ]);
		decryptingasymbol(coder, InBytesArray, InBytesArray_Length);
		// check the passwords or systemkeyt is Wrong
		if(coder->Result == coder->symbolsMaxCount){
			return 0;
		}
	}
	free(keytBuFF);
	return 1;
}
// decoded the hash value by InByteArray
int decryptingHashValue(WJLDeCoder *coder, unsigned char *InBytesArray, unsigned int InBytesArray_Length,const char *passwords, int passwords_Length, int HashValueBuFF_Length)
{
	int i = 0;
	// Initialize a new Bytes Array to Record the Hash Value
	unsigned char *HashValue;
	unsigned char *HashValueBuFF;
	HashValue = (unsigned char *)malloc(HashValueBuFF_Length);
	HashValueBuFF =  (unsigned char *)malloc(HashValueBuFF_Length);
	WJLHA3((unsigned char *)passwords, passwords_Length, SDRandomOfUCharTable, 256, HashValueBuFF, HashValueBuFF_Length);
	if(HashValue == NULL){
		return 0;
	}
	// decoding
	for(i = 0; i < HashValueBuFF_Length; ++i){
		decryptingasymbol(coder, InBytesArray, InBytesArray_Length);
		// check the passwords or systemkeyt is Wrong
		if(coder->Result == coder->symbolsMaxCount){
			return 0;
		}else{
			HashValue[i] = (unsigned char)coder->Result;
		}
	}
	// check the NewHashValue
	for(i = 0; i < HashValueBuFF_Length; ++i) {
		if(HashValue[i] != HashValueBuFF[i]) {
			return 0;
		}
	}
	free(HashValue);
	free(HashValueBuFF);
	return 1;
}
// decrypting the InBytesArray length
unsigned int decryptingInArraylength(WJLDeCoder *coder, unsigned char *InBytesArray, unsigned int InBytesArray_Length)
{
	unsigned int byteslength = 0x00;
	int i = 0;
	// decoding
	for(i = 0; i < 4; ++i){
		decryptingasymbol(coder, InBytesArray, InBytesArray_Length);
		//check the passwords or systemkeyt is Wrong
		if(coder->Result == coder->symbolsMaxCount){
			return 0;
		}else{
			byteslength = byteslength << 8;
			byteslength = byteslength | (unsigned char)coder->Result;
		}
	}
	if(byteslength != 0){
		coder->decodeOutBufferArray = (unsigned char *)realloc(coder->decodeOutBufferArray, byteslength + 2048);
	}
	return byteslength;
}

unsigned char* WJLWeightedDecode(WJLDeCoder *coder, const char *passwords, int passwords_Length, unsigned char *InByteArray, unsigned int InByteArray_length, unsigned int byteslength, unsigned int *OutByteArray_length)
{
	int i = 0;
	unsigned char *keytBuFF;
	int keytBuFF_Length = byteslength / 4;
	keytBuFF = (unsigned char *)malloc(keytBuFF_Length);
	// The Secret Key length is greater than the data length
	WJLHA3((unsigned char *)passwords, passwords_Length, SDRandomOfUCharTable, 256, keytBuFF, keytBuFF_Length);
	// start decoding InByteArray
	for(i = 0; i < byteslength ; ++ i){
		decryptingasymbol(coder, InByteArray, InByteArray_length);
		coder->coefficient = getDeCoefficient(i, (unsigned char)coder->Result ^ keytBuFF[ keytBuFF_Length - i % keytBuFF_Length - 1 ], keytBuFF[ i % keytBuFF_Length ]);
		OutPutDecode(coder, coder->Result);
	}
	*OutByteArray_length = coder->decodeOutBufferLoop;
	coder->decodeOutBufferLoop = 0;
	free(coder->SymbolsFreqArray);
	return coder->decodeOutBufferArray;
}
