#include "WJLSE.h"
// Random - generated byte 2D table,Customizable tables
unsigned char SERandomOfUCharTable[256] =	{
	0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
	0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
	0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
	0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
	0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
	0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
	0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
	0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
	0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
	0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
	0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
	0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
	0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
	0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
	0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
	0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16
};
// Initialize structure
void InitializeWJLEnCoder(WJLEnCoder *coder, const char *passwords, int passwords_Length)
{
	int i = 0;
	coder->rangeCodeBitsLenght = 31;
	coder->rangeCodeShiftBitsLenght = coder->rangeCodeBitsLenght - 8;
	coder->rangeCodeMaxIterval = 1 << coder->rangeCodeBitsLenght;
	coder->rangeCodeMinIterval = 1 << coder->rangeCodeShiftBitsLenght;
	coder->counterMaxFreq = 0x00FFFFL;
	coder->coefficient = 1.0;
	coder->encodeFlow = coder->rangeCodeMaxIterval;
	coder->encodeFlowRange = coder->rangeCodeMaxIterval;
	coder->encodeDelay = 0;
	coder->encodeDelayCount = 0;
	coder->encodeOutBufferLoop = 0;
	coder->Total = 0;
	coder->CumFreq = 0;
	coder->Freq = 0;
	coder->values = 0;
	coder->Result = 0;
	coder->ucChar = 0x00;
	// Initialize SymbolsFreqArray
	for(i = 0; i <= coder->symbolsMaxCount; ++i){
		coder->SymbolsFreqArray[i] = 1;
	}
	// Total is the Sum of all symbol's freq
	coder->Total = coder->symbolsMaxCount + 1;
	// Initialize S-Box by passwords
	for(i = 0; i < coder->symbolsMaxCount; ++i){
		coder->Sbox[i] = passwords[ i % passwords_Length ] ^ passwords[ ( i + 1 ) % passwords_Length ] ^ SERandomOfUCharTable[ i ];
	}
}
// Query 'SERandomOfUCharTable' table function
double getEnCoefficient(WJLEnCoder *coder, int index, unsigned char Symbol, const char *passwords, int passwords_Length)
{
	return 1.0 - (double)(((unsigned int)((unsigned char)passwords[  ((unsigned char)passwords[ index % passwords_Length ] ^ (unsigned char)passwords[ (index + 1) %  passwords_Length ]) % passwords_Length ]) * 256.0 + coder->Sbox[ ((Symbol ^ (unsigned char)passwords[ index % passwords_Length ]) % 16) * 16 + (Symbol ^ (unsigned char)passwords[ passwords_Length - (index % passwords_Length) ]) % 16 ])) / (100000000.0 + (unsigned char)passwords[ (index + 2) % passwords_Length ]);
};
// Gets the Random Bytes
void getEnRandomBytes(unsigned char *RandomBuFF, int RandomBuFF_Length)
{
	int i = 0;
	srand((int)time(0));
	for(i = 0;i < RandomBuFF_Length; ++i){
		RandomBuFF[i] = (unsigned char)random(255);
	}
}
// bytes encoding output
void OutPutEncode(WJLEnCoder *coder, int ucByte)
{
	coder->encodeOutBufferArray[coder->encodeOutBufferLoop] = (unsigned char)ucByte ^ coder->Sbox[ coder->encodeOutBufferLoop % coder->symbolsMaxCount ];
	coder->encodeOutBufferLoop += 1;
}
// When coding, calculate frequency
void EnGetFreq(WJLEnCoder *coder, int Symbol)
{
	int i = 0;
	unsigned int Sum = 0;
	if(Symbol == 0){
		coder->CumFreq = 0;
		coder->Freq = coder->SymbolsFreqArray[0];
		return;
	}
	// get the cumulative distribution function
	for(i = 0; i < Symbol; ++i) {
		Sum += coder->SymbolsFreqArray[i];
	}
	coder->Freq = coder->SymbolsFreqArray[Symbol];
	coder->CumFreq = Sum;
}
// Cumulative and reduced frequency
void EnIncFreq(WJLEnCoder *coder, int Symbol)
{
	int i = 0;
	unsigned int NewFreq = 0, Sum = 0;
	// Synchronously subtracts the statistics of each symbol
	if(coder->Total == coder->counterMaxFreq){
		for(i = 0; i <= coder->symbolsMaxCount; ++i) {
			NewFreq = coder->SymbolsFreqArray[i] >> 1;
			if(NewFreq == 0) {
				coder->SymbolsFreqArray[i] = 1;
			}else{
				coder->SymbolsFreqArray[i] = NewFreq;
			}
			Sum += coder->SymbolsFreqArray[i];
		}
		coder->Total = Sum;
	}
	// this symbol freq Add 1
	coder->SymbolsFreqArray[Symbol] ++;
	// All symbol freq Add 1
	coder->Total += 1;
}
// Encode by Adaptive weighted probability model
void SEEncode(WJLEnCoder *coder)
{
	unsigned int High;
	int i = 0;
	// Value of distribution function for weighted probability model
	coder->encodeFlowRange = coder->encodeFlowRange / coder->Total;
	coder->encodeFlowRange =(unsigned int)((double)coder->encodeFlowRange *  coder->coefficient); 
	coder->encodeFlow += coder->CumFreq * coder->encodeFlowRange;
	coder->encodeFlowRange *= coder->Freq;

	while (coder->encodeFlowRange <= coder->rangeCodeMinIterval) {
		High = coder->encodeFlow + coder->encodeFlowRange - 1;
		if (coder->encodeDelayCount != 0) {
			if (High <= coder->rangeCodeMaxIterval) {
				OutPutEncode(coder, coder->encodeDelay);
				for (i = 1; i <= coder->encodeDelayCount - 1; ++i) {
					OutPutEncode(coder, 0xFF);
				}
				coder->encodeDelayCount = 0;
				coder->encodeFlow += coder->rangeCodeMaxIterval;
			} else if (coder->encodeFlow >= coder->rangeCodeMaxIterval) {
				OutPutEncode(coder, coder->encodeDelay + 1);
				for (i = 1; i <= coder->encodeDelayCount - 1; ++i) {
					OutPutEncode(coder, 0x00);
				}
				coder->encodeDelayCount = 0;
			} else {
				coder->encodeDelayCount ++;
				coder->encodeFlow = (coder->encodeFlow << 8) & (coder->rangeCodeMaxIterval - 1);
				coder->encodeFlowRange <<= 8;
				continue;
			}
		}
		if (((coder->encodeFlow ^ High) & (0x00FF << coder->rangeCodeShiftBitsLenght)) == 0) {
			OutPutEncode(coder, (int) (coder->encodeFlow >> coder->rangeCodeShiftBitsLenght));
		} else {
			coder->encodeFlow -= coder->rangeCodeMaxIterval;
			coder->encodeDelay = coder->encodeFlow >> coder->rangeCodeShiftBitsLenght;
			coder->encodeDelayCount = 1;
		}
		coder->encodeFlow = ((coder->encodeFlow << 8) & (coder->rangeCodeMaxIterval - 1))
			| (coder->encodeFlow & coder->rangeCodeMaxIterval);
		coder->encodeFlowRange <<= 8;
	}
}
//To Finish Encode
void SEFinishEncode(WJLEnCoder *coder)
{
	int n = 0;
	if (coder->encodeDelayCount != 0) {
		if (coder->encodeFlow < coder->rangeCodeMaxIterval) {
			OutPutEncode(coder, coder->encodeDelay);
			for (n = 1; n <= coder->encodeDelayCount - 1; n++) {
				OutPutEncode(coder, 0xFF);
			}
		} else {
			OutPutEncode(coder, coder->encodeDelay + 1);
			for (n = 1; n <= coder->encodeDelayCount - 1; n++) {
				OutPutEncode(coder, 0x00);
			}
		}
	}
	coder->encodeFlow <<= 1;
	n = coder->rangeCodeBitsLenght + 1;
	do {
		n -= 8;
		OutPutEncode(coder, (int) (coder->encodeFlow >> n));
	} while ( n > 0 );
}
// encrypting a symbol
void encryptingASymbol(WJLEnCoder *coder,int symbol)
{
	EnGetFreq(coder, symbol);
	SEEncode(coder);
	EnIncFreq(coder, symbol);
}
// encrypting the end symbol
void EncryptingTheEndSymbol(WJLEnCoder *coder)
{
	encryptingASymbol(coder, coder->symbolsMaxCount);
	SEFinishEncode(coder);
}
// encrypting the Random byte 
void EncryptingTheRandomBytes(WJLEnCoder *coder, const char *passwords, int passwords_Length)
{
	int i = 0, symbol = 0;
	getEnRandomBytes(coder->RandomBytes, coder->RandomBytes_Length);
	for(i = 0; i < coder->RandomBytes_Length; ++ i) {
		symbol = (int)coder->RandomBytes[i];
		encryptingASymbol(coder, symbol);
		coder->coefficient = getEnCoefficient(coder, i, symbol, passwords, passwords_Length);
	}
}
// encrypting the length
void EncryptingFileLength(WJLEnCoder *coder, unsigned int InArrayLength, const char *passwords, int passwords_Length)
{
	int symbol = 0;
	symbol = (int)((InArrayLength >> 24) & 0x00FF);
	encryptingASymbol(coder, symbol);
	coder->coefficient = getEnCoefficient(coder, coder->RandomBytes_Length + 1, symbol, passwords, passwords_Length);
	symbol = (int)((InArrayLength >> 16) & 0x00FF);
	encryptingASymbol(coder, symbol);
	coder->coefficient = getEnCoefficient(coder, coder->RandomBytes_Length + 2, symbol, passwords, passwords_Length);
	symbol = (int)((InArrayLength >> 8) & 0x00FF);
	encryptingASymbol(coder, symbol);
	coder->coefficient = getEnCoefficient(coder, coder->RandomBytes_Length + 3, symbol, passwords, passwords_Length);
	symbol = (int)(InArrayLength & 0x00FF);
	encryptingASymbol(coder, symbol);
	coder->coefficient = getEnCoefficient(coder, coder->RandomBytes_Length + 4, symbol, passwords, passwords_Length);
}
// encrypting the datas
void WJLWeightedEncode(WJLEnCoder *coder, const char *passwords, int passwords_Length, unsigned char *InByteArray, unsigned int InByteArray_length, unsigned int *OutByteArray_length)
{
	int i = 0, symbol = 0;
	// start encoding InByteArray
	for(i = 0; i < InByteArray_length ; ++ i){
		symbol = (int)InByteArray[i];
		encryptingASymbol(coder, symbol);
		coder->coefficient = getEnCoefficient(coder, coder->RandomBytes_Length + 4 + i, symbol, passwords, passwords_Length);
	}
	// End Encrypting
	EncryptingTheEndSymbol(coder);
	// return
	*OutByteArray_length = coder->encodeOutBufferLoop;
}
